list_manual_updates() {
  cat <<- EOF
	:: You need to manually update:
	:: - password for Chestnut pacman repository
	:: - private key for Chestnut WireGuard connection
	EOF
}

post_install() {
  useradd -U damien 2> /dev/null

  # logs
  install -dm0755 -o damien -g damien /var/log/sway
  install -Dm0644 -o damien -g damien /dev/null /var/log/sway/sway.log

  # LXD setup
  systemctl start lxd.service
  lxd init --minimal

  list_manual_updates
}
