#!/bin/sh
# commands used:
# - column
# - pacman

init_variables() {
  COMMAND=${0##*/}


  # modified at installation
  BLACKLIST="/boot/grub/grub.cfg"
  BLACKLIST="${BLACKLIST}:/etc/crypttab"
  BLACKLIST="${BLACKLIST}:/etc/default/grub"
  BLACKLIST="${BLACKLIST}:/etc/fstab"
  BLACKLIST="${BLACKLIST}:/etc/group"
  BLACKLIST="${BLACKLIST}:/etc/gshadow"
  BLACKLIST="${BLACKLIST}:/etc/hosts"
  BLACKLIST="${BLACKLIST}:/etc/locale.gen"
  BLACKLIST="${BLACKLIST}:/etc/mkinitcpio.conf"
  BLACKLIST="${BLACKLIST}:/etc/pacman.d/mirrorlist"
  BLACKLIST="${BLACKLIST}:/etc/passwd"
  BLACKLIST="${BLACKLIST}:/etc/shadow"
  BLACKLIST="${BLACKLIST}:/etc/shells"

  # modified by own system-config package
  BLACKLIST="${BLACKLIST}:/etc/bluetooth/main.conf"
  BLACKLIST="${BLACKLIST}:/etc/issue"
  BLACKLIST="${BLACKLIST}:/etc/logrotate.conf"
  BLACKLIST="${BLACKLIST}:/etc/pacman.conf"

  # misc
  BLACKLIST="${BLACKLIST}:/etc/resolv.conf"
}

show_usage() {
  cat <<- EOF
	usage: ${COMMAND} [<options>]

	List modified package files alongside the package they belong to.
	Valid known modifications are ignored

	Needs to be run as a root user

	Options:
	  -h    show this message only
	EOF
}

parse_command_line() {
  while getopts h OPT; do
    case "${OPT}" in
      h) show_usage; exit 0 ;;
      ?) exit_error ;;
    esac
  done

  shift $(( OPTIND - 1 ))
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  echo "Try '${COMMAND} -h' for more information."
  exit 1
} >&2

check_root_user() {
  [ "$( id -u )" -ne 0 ] && exit_error 'The script must be run as root'
}

list_files() {
  pacman -Qii \
    | awk '/^MODIFIED/ { print $2 }' \
    | grep -vE "$( echo "${BLACKLIST}" | tr ':' '|' )" \
    | xargs -I{} sh -c "{ pacman -Qoq {}; echo {}; } | paste -s -" \
    | sort \
    | column -t
}

init_variables
parse_command_line "$@"

check_root_user

list_files
