#!/bin/sh

CONTAINER_NAME='arch-builds'

lxc launch "images:archlinux" "${CONTAINER_NAME}"

# wait for network
sleep 2

cat << EOF | lxc exec "${CONTAINER_NAME}" -- /bin/sh
  pacman -S --noconfirm base-devel git
  useradd -mU damien
  echo 'damien ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
EOF

# share builds folder with rw permissions
lxc config device add "${CONTAINER_NAME}" builds disk \
  source="$( project-path repo arch-system )/builds" \
  path="/home/damien/builds"
lxc config set "${CONTAINER_NAME}" raw.idmap='both 1000 1000'

# share SSH agent
lxc config device add "${CONTAINER_NAME}" ssh-agent proxy \
  "connect=unix:$( echo "${SSH_AUTH_SOCK}" | cut -f2 -d= )" \
  listen=unix:/home/damien/.ssh-agent.sock \
  bind=container \
  uid=1000 \
  gid=1000 \
  mode=0600 \
  security.uid=1000 \
  security.gid=1000

# rsync usage to chestnut
cat << EOF | lxc exec "${CONTAINER_NAME}" -- /bin/sh
  pacman -S --noconfirm openssh rsync
  echo 'export SSH_AUTH_SOCK=/home/damien/.ssh-agent.sock' >> /home/damien/.bash_profile
  mkdir /home/damien/.ssh
  cat <<- EOF2 > /home/damien/.ssh/config
		Host chestnut
		    Hostname tardypad.me
		    User damien
		    Port 11235
EOF2
  cat <<- EOF3 > /home/damien/.ssh/known_hosts
		[tardypad.me]:11235 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC5J5EBaMQMDWF4AoFimunwgyM06W4EIlovUfugaHBJb
		[tardypad.me]:11235 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+8OMttV7OSWlUbvoFp8gsVsk3d1KNMdshJ+E1FDFRy5g0/vuPKkEmVUTiMBWSPrY3yax5hxb13KXyBHAdnfimLqoA3K8NWGqjViw00lJ2Pmj9tpw/zSpMxH5yaXsQWJqW+TduArZBRyK3j26IGWwSyazBEGpdbcrDkdchsL2ubG56Cg44QYaXxmnpZL1auPmlunDDRLMdrUsBKZUg6+1bYvxNn1IljFt+PZ07UUEyZCFIiHccF0SW7NNUcg+0JRgb4UXKtJWsFBU9Mc1UsFTJIcp1VAu4phXs7I986EeKsx0LlcA6NmzPntGxkulxkRqpp17ac3k/+/NyysOMDk0XeVBp9xM7OXq51JAi/Spsx22epHH4x/y/+RQSbTzttneptct+0ca+5gdASJE3N7m4PxLBznpPAxt57NOXceTbC/h/LVGVt+Av9xkNlmmxpS9A4YzqAfBydduozzbioMshmx71Bn9PcPuEjd/lBwVokcRHUt2zfGSGTm3e2/vs1F8=
		[tardypad.me]:11235 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJc0zSYFI6QxUgJaQdrdkVdASIyTq55I3n/Mg+2PErRxWaGgpf6wTyiK7rDam3TzVHISoPq41i2lcHDW9E798j0=
EOF3
  chown -R damien:damien /home/damien/.ssh
EOF

lxc restart "${CONTAINER_NAME}"
