#!/bin/sh
# commands used:
# - pacman

init_variables() {
  COMMAND=${0##*/}
}

show_usage() {
  cat <<- EOF
	usage: ${COMMAND} [<options>]

	Setup a new system after basic Arch installation

	Needs to be run from the repository root as a root user

	Options:
	  -h    show this message only
	EOF
}

parse_command_line() {
  while getopts h OPT; do
    case "${OPT}" in
      h) show_usage; exit 0 ;;
      ?) exit_error ;;
    esac
  done

  shift $(( OPTIND - 1 ))
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  echo "Try '${COMMAND} --help' for more information."
  exit 1
} >&2

check_root_user() {
  [ "$( id -u )" -ne 0 ] && exit_error 'The script must be run as root'
}

update_current_packages() {
  pacman -Syu --noconfirm
}

setup_repositories() {
  # set own repo HTTP credentials
  echo 'Enter pkgs.tardypad.me HTTP credentials'
  printf 'username: '; read -r USERNAME
  printf 'password: '; read -r PASSWORD

  # reuse pacman config from system-config package
  mkdir -p /etc/pacmand.d/
  cp builds/system-config/etc-pacman /etc/pacman.conf
  sed -e "s/{USERNAME}/${USERNAME}/" -e "s/{PASSWORD}/${PASSWORD}/" \
    builds/system-config/etc-pacman-aur > /etc/pacman.d/aur
  sed -e "s/{USERNAME}/${USERNAME}/" -e "s/{PASSWORD}/${PASSWORD}/" \
    builds/system-config/etc-pacman-tardypad > /etc/pacman.d/tardypad
  chmod 644 /etc/pacman.conf /etc/pacman.d/aur /etc/pacman.d/tardypad
}

install_packages() {
  PACKAGES=$(
    cut -d' ' -f1 lists/* \
      | grep -v -E '^system-config|^dotfiles'
  )

  pacman -Sy --noconfirm ${PACKAGES}

  CUSTOM_PACKAGES=$(
    cut -d' ' -f1 lists/* \
      | grep -E '^system-config|^dotfiles'
  )

  pacman -S --noconfirm --overwrite '*' ${CUSTOM_PACKAGES}
}

system_setup() {
  update_current_packages
  setup_repositories
  install_packages
}

init_variables
parse_command_line "$@"

check_root_user
system_setup
