#!/bin/sh
# commands used:
# - doas
# - mktemp
# - pacman

TMP_DIR="$( mktemp -d )"
trap 'rm -rf "${TMP_DIR}"' EXIT

doas pacman -S --noconfirm wine winetricks lib32-gnutls

export WINEPREFIX="${HOME}/.wine-ade"
export WINEARCH=win32

BIN_DIR="${HOME}/.local/bin"

wineboot
winetricks -q corefonts
winetricks -q windowscodecs
winetricks -q dotnet35sp1

curl -L http://download.adobe.com/pub/adobe/digitaleditions/ADE_2.0_Installer.exe \
  -o "${TMP_DIR}/ade_installer.exe"

wine "${TMP_DIR}/ade_installer.exe"

mkdir -p "${BIN_DIR}"
cat << EOF | doas tee "${BIN_DIR}/adobe-digital-editions"
#!/bin/sh
WINEPREFIX="${WINEPREFIX}" wine "${WINEPREFIX}/drive_c/Program Files/Adobe/Adobe Digital Editions 2.0/DigitalEditions.exe"
EOF
doas chmod +x "${BIN_DIR}/adobe-digital-editions"
