#!/bin/sh
# commands used:
# - chsh
# - doas
# - mitmproxy
# - pacman
# - passwd
# - timeout
# - trust
# - useradd
# - usermod


init_variables() {
  COMMAND=${0##*/}
}

show_usage() {
  cat <<- EOF
	usage: ${COMMAND} [<options>]

	Setup a new system after basic Arch installation

	Needs to be run as a root user

	Options:
	  -h    show this message only
	EOF
}

parse_command_line() {
  while getopts h OPT; do
    case "${OPT}" in
      h) show_usage; exit 0 ;;
      ?) exit_error ;;
    esac
  done

  shift $(( OPTIND - 1 ))
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  echo "Try '${COMMAND} -h' for more information."
  exit 1
} >&2

check_root_user() {
  [ "$( id -u )" -ne 0 ] && exit_error 'The script must be run as root'
}

upgrade_current_packages() {
  pacman -Syu --noconfirm
}

setup_repositories() {
  echo 'Enter pkgs.tardypad.me HTTP credentials'
  printf 'username: '; read -r USERNAME
  printf 'password: '; read -r PASSWORD

  cat >> /etc/pacman.conf <<- EOF
	[tardypad]
	SigLevel = Optional TrustAll
	Server = https://${USERNAME}:${PASSWORD}@pkgs.tardypad.me/arch/tardypad

	[aur]
	SigLevel = Optional TrustAll
	Server = https://${USERNAME}:${PASSWORD}@pkgs.tardypad.me/arch/aur
	EOF
}

install_packages() {
  pacman -S --overwrite '*' system-config
}

setup_users() {
  usermod -aG uucp,video,wheel,input,wireshark,lxd damien
  passwd damien

  chsh -s /usr/bin/zsh damien
  chsh -s /usr/bin/zsh root
}

setup_proxy() {
  # creates keys for CA and trust it
  useradd -m proxyer
  timeout 1s doas -u proxyer mitmproxy
  trust anchor --store /home/proxyer/.mitmproxy/mitmproxy-ca.pem

  # reuse same keys locally (creating new ones seems to create issues on usage)
  cp -r /home/proxyer/.mitmproxy/ /home/damien/.mitmproxy
  chown -R damien:damien /home/damien/.mitmproxy
}

init_variables
parse_command_line "$@"

check_root_user

setup_repositories
upgrade_current_packages
install_packages
setup_users
setup_proxy
