#!/bin/sh
# commands used:
# - pacman

init_variables() {
  COMMAND=${0##*/}
}

show_usage() {
  cat <<- EOF
	usage: ${COMMAND} [<options>]

	Setup a new system after basic Arch installation

	Needs to be run as a root user

	Options:
	  -h    show this message only
	EOF
}

parse_command_line() {
  while getopts h OPT; do
    case "${OPT}" in
      h) show_usage; exit 0 ;;
      ?) exit_error ;;
    esac
  done

  shift $(( OPTIND - 1 ))
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  echo "Try '${COMMAND} -h' for more information."
  exit 1
} >&2

check_root_user() {
  [ "$( id -u )" -ne 0 ] && exit_error 'The script must be run as root'
}

update_current_packages() {
  pacman -Syu --noconfirm
}

setup_repositories() {
  echo 'Enter pkgs.tardypad.me HTTP credentials'
  printf 'username: '; read -r USERNAME
  printf 'password: '; read -r PASSWORD

  cat >> /etc/pacman.conf <<- EOF
	[tardypad]
	SigLevel = Optional TrustAll
	Server = https://${USERNAME}:${PASSWORD}@pkgs.tardypad.me/tardypad

	[aur]
	SigLevel = Optional TrustAll
	Server = https://${USERNAME}:${PASSWORD}@pkgs.tardypad.me/aur
	EOF
}

install_packages() {
  pacman -S --overwrite '*' system-config
}

setup_users() {
  useradd -mU -s /usr/bin/zsh -G uucp,video,wheel,input damien
  passwd damien

  chsh -s /usr/bin/zsh root

  mkdir -p /home/damien/Contacts
  mkdir -p /home/damien/Desktop
  mkdir -p /home/damien/Downloads
  mkdir -p /home/damien/Documents
  mkdir -p /home/damien/Music
  mkdir -p /home/damien/Notes
  mkdir -p /home/damien/Pictures
  mkdir -p /home/damien/Projects
  mkdir -p /home/damien/Videos

  chown -R damien:damien /home/damien
}

init_variables
parse_command_line "$@"

check_root_user

setup_repositories
update_current_packages
install_packages
setup_users
